### PR TITLE
Sorted the "ignoreSubreddits" alphabetically

### PR DESCRIPTION
**Pull request by alexrecuenco**
It would be easier for someone to update this list if it is sorted. I used `sort -bf <file>` to make the sorting.

### CODE REVIEW

**Comment by wasdennnoch** [comment]
Thing is, right now I update it manually using PMs and just add a new item at the bottom whenever I receive a ban. In the future I'll extract the list into a database (including ban reason, time etc) so sorting this list here doesn't really serve that much of a purpose. It's also already outdated and why would someone else need to update the list? Yes, it may be easier to look through but as said I'll refactor that stuff anyway. Thanks for your PR though.

**Comment by alexrecuenco** [comment]
Alright, sorry for bothering you then. I was just looking through your bot (great simple bot) and I ordered that list just to look through it, and I thought I might share that.

**Comment by wasdennnoch** [comment]
I've been wanting to create a website where you can see a bunch of stats about the bot for over half a year now, don't know when I'll actually complete it. On there you're supposed to also see things such as the ban list and filter them by various aspects ;)

**Comment by alexrecuenco** [comment]
That will be a nice site to look at once it is up and running ;)

Let me know if you are looking for help.

**Pull request closed without merging**
